#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import urllib.request
from collections import OrderedDict
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


ROOT = Path(__file__).resolve().parents[1]
SOURCES_FILE = ROOT / "sources.json"
CACHE_DIR = ROOT / "cache"
DIST_DIR = ROOT / "dist"
DEFAULT_PROFILE = Path("/Users/xiaoyuan/Downloads/origo15.yaml")

RULE_PREFIXES_LITE = (
    "DOMAIN,",
    "DOMAIN-SUFFIX,",
    "DOMAIN-KEYWORD,",
    "IP-CIDR,",
    "IP-CIDR6,",
    "IP-ASN,",
)

SECTION_ORDER = ["Rule", "URL Rewrite", "Rewrite", "Map Local"]
POWERFUL_SECTION_ORDER = ["Argument", "General", "Rule", "URL Rewrite", "Rewrite", "Body Rewrite", "Map Local", "Script", "MITM"]


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def fetch_text(url: str, cache_path: Path, use_cache: bool, user_agent: str | None = None) -> str:
    if use_cache and cache_path.exists():
        return cache_path.read_text(encoding="utf-8", errors="replace")

    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": user_agent or "origo-ad/1.0",
            "Referer": "https://loonlab.103516.xyz/Plugin/",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as res:
        data = res.read().decode("utf-8", errors="replace")
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    cache_path.write_text(data, encoding="utf-8")
    return data


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def parse_sections(text: str) -> Tuple[List[str], Dict[str, List[str]]]:
    meta: List[str] = []
    sections: Dict[str, List[str]] = OrderedDict()
    current: str | None = None

    for raw in text.splitlines():
        line = raw.rstrip()
        match = re.match(r"^\[(.+)]$", line.strip())
        if match:
            current = normalize_section(match.group(1).strip())
            sections.setdefault(current, [])
            continue

        if current is None:
            if line.startswith("#!"):
                meta.append(line)
            continue

        sections.setdefault(current, []).append(line)

    return meta, sections


def normalize_section(section: str) -> str:
    normalized = section.strip()
    if normalized.lower() == "mitm":
        return "MITM"
    return normalized


def meaningful_entries(lines: Iterable[str]) -> List[str]:
    entries: List[str] = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        entries.append(stripped)
    return entries


def dedupe_keep_order(entries: Iterable[str]) -> List[str]:
    seen = set()
    result = []
    for entry in entries:
        if entry in seen:
            continue
        seen.add(entry)
        result.append(entry)
    return result


def lite_rule_filter(entry: str) -> bool:
    upper = entry.upper()
    return upper.startswith(RULE_PREFIXES_LITE)


def balanced_rewrite_filter(entry: str) -> bool:
    lower = entry.lower()
    heavy_markers = (
        "response-body",
        "script-path",
        "requires-body",
        "jq-path",
        " request-body",
        " http-response",
        " http-request",
    )
    return not any(marker in lower for marker in heavy_markers)


def build_module(
    name: str,
    source_records: List[dict],
    kept_sections: Dict[str, List[str]],
    dropped_note: str,
    build_id: str,
    section_order: List[str] | None = None,
) -> str:
    lines = [
        f"#!name={name}",
        "#!desc=面向省电优化的 Egern 去广告模块，由仍在维护的上游规则自动生成。",
        "#!author=Generated by origo-ad",
        "#!homepage=https://github.com/miloquinn/origo-ad",
        f"#!generated-source-sha256={build_id}",
        f"#!generated-note={dropped_note}",
        "",
        "# Sources:",
    ]
    for record in source_records:
        lines.append(f"# - {record['name']}: {record['url']}")
    lines.append("")

    for section in section_order or SECTION_ORDER:
        entries = kept_sections.get(section, [])
        if not entries:
            continue
        lines.append(f"[{section}]")
        lines.extend(entries)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def source_stats(sections: Dict[str, List[str]]) -> Dict[str, int]:
    stats = {}
    for section, lines in sections.items():
        stats[section] = len(meaningful_entries(lines))
    return stats


def make_snippet(lite_url: str, balanced_url: str, powerful_url: str) -> str:
    return f"""# 省电版模块接入片段
# 先用 lite。如果广告明显变多，再把 lite 的 enabled 改 false，balanced 改 true。
# powerful 是最强档，包含脚本/MITM/响应体处理，去广告强但更耗电，默认别开。
# 注意：把下面的 URL 替换成你实际发布后的 HTTPS 地址。

modules:
- name: Origo Ad Lite
  url: {lite_url}
  enabled: true
- name: Origo Ad Balanced
  url: {balanced_url}
  enabled: false
- name: Origo Ad Powerful
  url: {powerful_url}
  enabled: false
- url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/Surge/module/blockAds.module
  enabled: false
- url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Surge/AdvertisingLite/AdvertisingLite.sgmodule
  enabled: false

# 如果要进一步省电，建议把 scriptings 里的 YouTube/Bilibili/X 响应脚本也先关掉。
# 那几条脚本需要 body_required，比普通域名拦截重很多。
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Build battery-oriented Egern adblock modules.")
    parser.add_argument("--profile", type=Path, default=DEFAULT_PROFILE, help="Existing Egern profile for context.")
    parser.add_argument("--no-profile", action="store_true", help="Do not inspect the existing Egern profile.")
    parser.add_argument("--use-cache", action="store_true", help="Use cached upstream modules if present.")
    parser.add_argument(
        "--base-url",
        default="https://example.com/egern",
        help="Base URL used in the generated snippet. Replace it with your real hosted URL.",
    )
    args = parser.parse_args()

    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    DIST_DIR.mkdir(parents=True, exist_ok=True)

    sources = read_json(SOURCES_FILE)["sources"]
    report = {
        "generated_from": "upstream source hashes",
        "profile": None,
        "sources": [],
        "tiers": {},
    }

    all_lite_rules: List[str] = []
    all_balanced: Dict[str, List[str]] = {"Rule": [], "URL Rewrite": [], "Rewrite": [], "Map Local": []}
    all_powerful: Dict[str, List[str]] = {section: [] for section in POWERFUL_SECTION_ORDER}
    source_hashes: List[str] = []

    for source in sources:
        cache_path = CACHE_DIR / f"{source['name']}.module"
        text = fetch_text(source["url"], cache_path, args.use_cache, source.get("user_agent"))
        source_hash = sha256_text(text)
        source_hashes.append(source_hash)
        _meta, sections = parse_sections(text)
        stats = source_stats(sections)
        rules = meaningful_entries(sections.get("Rule", []))
        lite_rules = [entry for entry in rules if lite_rule_filter(entry)]
        balanced_rules = rules
        url_rewrites = meaningful_entries(sections.get("URL Rewrite", []))
        rewrites = meaningful_entries(sections.get("Rewrite", []))
        balanced_rewrites = [entry for entry in rewrites if balanced_rewrite_filter(entry)]
        map_locals = meaningful_entries(sections.get("Map Local", []))

        all_lite_rules.extend(lite_rules)
        all_balanced["Rule"].extend(balanced_rules)
        all_balanced["URL Rewrite"].extend(url_rewrites)
        all_balanced["Rewrite"].extend(balanced_rewrites)
        all_balanced["Map Local"].extend(map_locals)
        for section in POWERFUL_SECTION_ORDER:
            all_powerful[section].extend(meaningful_entries(sections.get(section, [])))

        report["sources"].append(
            {
                "name": source["name"],
                "url": source["url"],
                "sha256": source_hash,
                "raw_counts": stats,
                "kept_lite_rule_count": len(lite_rules),
                "kept_balanced_counts": {
                    "Rule": len(balanced_rules),
                    "URL Rewrite": len(url_rewrites),
                    "Rewrite": len(balanced_rewrites),
                    "Map Local": len(map_locals),
                },
                "kept_powerful_counts": {
                    section: len(meaningful_entries(sections.get(section, [])))
                    for section in POWERFUL_SECTION_ORDER
                    if meaningful_entries(sections.get(section, []))
                },
                "dropped_sections": {
                    "lite": ["URL-REGEX in Rule", "URL Rewrite", "Body Rewrite", "Map Local", "Script"],
                    "balanced": ["Body Rewrite", "Script"],
                    "powerful": [],
                },
            }
        )

    lite_sections = {"Rule": dedupe_keep_order(all_lite_rules)}
    balanced_sections = {section: dedupe_keep_order(entries) for section, entries in all_balanced.items()}
    powerful_sections = {section: dedupe_keep_order(entries) for section, entries in all_powerful.items()}

    source_records = [{"name": item["name"], "url": item["url"]} for item in sources]
    build_id = hashlib.sha256("\n".join(source_hashes).encode("utf-8")).hexdigest()
    lite_module = build_module(
        "Origo Ad Lite",
        source_records,
        lite_sections,
        "Keeps low-cost domain/IP rules only; drops URL regex/rewrite/map-local/body/script processing.",
        build_id,
    )
    balanced_module = build_module(
        "Origo Ad Balanced",
        source_records,
        balanced_sections,
        "Keeps rules, URL rewrite, and map local; drops body rewrite and scripts.",
        build_id,
    )
    powerful_module = build_module(
        "Origo Ad Powerful",
        source_records,
        powerful_sections,
        "Maximum ad blocking; keeps rule, rewrite, map local, body rewrite, script, and MITM sections.",
        build_id,
        POWERFUL_SECTION_ORDER,
    )

    lite_path = DIST_DIR / "origo-ad-lite.module"
    balanced_path = DIST_DIR / "origo-ad-balanced.module"
    powerful_path = DIST_DIR / "origo-ad-powerful.module"
    lite_path.write_text(lite_module, encoding="utf-8")
    balanced_path.write_text(balanced_module, encoding="utf-8")
    powerful_path.write_text(powerful_module, encoding="utf-8")

    base = args.base_url.rstrip("/")
    snippet = make_snippet(
        f"{base}/origo-ad-lite.module",
        f"{base}/origo-ad-balanced.module",
        f"{base}/origo-ad-powerful.module",
    )
    (DIST_DIR / "origo15-module-snippet.yaml").write_text(snippet, encoding="utf-8")

    if not args.no_profile and args.profile.exists():
        profile_text = args.profile.read_text(encoding="utf-8", errors="replace")
        report["profile"] = {
            "path": str(args.profile),
            "enabled_heavy_modules_seen": [
                url
                for url in [
                    "https://raw.githubusercontent.com/fmz200/wool_scripts/main/Surge/module/blockAds.module",
                    "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Surge/AdvertisingLite/AdvertisingLite.sgmodule",
                ]
                if url in profile_text
            ],
            "body_required_count": profile_text.count("body_required: true"),
            "scriptings_section_seen": "scriptings:" in profile_text,
            "mitm_section_seen": "mitm:" in profile_text,
        }

    report["tiers"] = {
        "lite": {
            "path": str(lite_path.relative_to(ROOT)),
            "counts": {section: len(entries) for section, entries in lite_sections.items()},
        },
        "balanced": {
            "path": str(balanced_path.relative_to(ROOT)),
            "counts": {section: len(entries) for section, entries in balanced_sections.items()},
        },
        "powerful": {
            "path": str(powerful_path.relative_to(ROOT)),
            "counts": {section: len(entries) for section, entries in powerful_sections.items() if entries},
        },
    }
    (DIST_DIR / "build-report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"wrote {lite_path}")
    print(f"wrote {balanced_path}")
    print(f"wrote {powerful_path}")
    print(f"wrote {DIST_DIR / 'origo15-module-snippet.yaml'}")
    print(f"wrote {DIST_DIR / 'build-report.json'}")
    print("lite counts:", report["tiers"]["lite"]["counts"])
    print("balanced counts:", report["tiers"]["balanced"]["counts"])
    print("powerful counts:", report["tiers"]["powerful"]["counts"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
